import { solveStage, parseGridToState } from '../src/utils/solver';

const candidateStages = [
  // STAGE 21: BOX ROTATION (상자 회전) - 2 balls, 2 targets
  {
    id: 21,
    name: '21. Box Rotation (상자 회전)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 8,
    height: 7,
    description: '공 2개를 시계 방향으로 회전시켜 원하는 모서리 집으로 넣으세요.',
    hint: '중앙 벽을 회전축으로 활용하세요.',
    grid: [
      '########',
      '#@.....#',
      '#.O.##.#',
      '#...##.#',
      '#.O.XX.#',
      '#......#',
      '########',
    ],
  },
  // STAGE 22: PINBALL RUN (핀볼 런)
  {
    id: 22,
    name: '22. Pinball Run (핀볼 런)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 8,
    height: 7,
    description: '지그재그 핀볼 장애물을 통과하여 하단 2개의 집으로 골인시키세요.',
    hint: '위쪽 공을 먼저 통로 입구로 정렬하세요.',
    grid: [
      '########',
      '#@.....#',
      '#.O.#..#',
      '#...#.O#',
      '#.X.#.X#',
      '#......#',
      '########',
    ],
  },
  // STAGE 23: CORRIDOR SHUFFLE (복도 셔플)
  {
    id: 23,
    name: '23. Corridor Shuffle (복도 셔플)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 8,
    height: 7,
    description: '일자 복도에서 공들의 순서를 뒤바꾸는 고급 소코반 스킬이 필요합니다.',
    hint: '우측 대피소 공간을 활용해 순서를 바꾸세요.',
    grid: [
      '########',
      '#@.....#',
      '#.O.O..#',
      '#...##.#',
      '#.XX#..#',
      '#......#',
      '########',
    ],
  },
  // STAGE 24: TETRIS T-SPIN (T자 창고)
  {
    id: 24,
    name: '24. Tetris T-Spin (T자 창고)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 8,
    height: 7,
    description: 'T자 형태의 분기 구역에서 2개의 공을 제어하세요.',
    hint: '가장 깊은 홈에 들어갈 공을 먼저 선별하세요.',
    grid: [
      '########',
      '#@.....#',
      '#..O.O.#',
      '#.###..#',
      '#..X.X.#',
      '#......#',
      '########',
    ],
  },
  // STAGE 25: DOUBLE LOCK (이중 잠금)
  {
    id: 25,
    name: '25. Double Lock (이중 잠금)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 8,
    height: 7,
    description: '2개의 공이 서로의 진로를 가로막고 있는 퍼즐입니다.',
    hint: '바깥쪽 공을 넓은 구역으로 임시 피신시키세요.',
    grid: [
      '########',
      '#@.....#',
      '#.##.O.#',
      '#X.O...#',
      '#.##.X.#',
      '#......#',
      '########',
    ],
  },
  // STAGE 26: THE SPIRAL (나선 미로)
  {
    id: 26,
    name: '26. The Spiral (나선 미로)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 8,
    height: 8,
    description: '나선형 벽을 따라 돌면서 공 2개를 목적지까지 운반하세요.',
    hint: '코너를 돌 때 캐릭터가 들어갈 수 있는 틈을 남겨두세요.',
    grid: [
      '########',
      '#@.....#',
      '#.####.#',
      '#.#..#.#',
      '#.#O.#.#',
      '#.#XOX.#',
      '#......#',
      '########',
    ],
  },
  // STAGE 27: FOUR CORNERS (동서남북)
  {
    id: 27,
    name: '27. Four Corners (동서남북)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 9,
    height: 9,
    description: '중앙에서 4방향으로 뻗어나가는 4채의 집에 공 4개를 배치하세요.',
    hint: '한 방향씩 완전하게 클리어하며 전진하세요.',
    grid: [
      '..#####..',
      '..#...#..',
      '###.X.###',
      '#...O...#',
      '#X.O@O.X#',
      '#...O...#',
      '###.X.###',
      '..#...#..',
      '..#####..',
    ],
  },
  // STAGE 28: PILLAR MAZE (기둥 미로)
  {
    id: 28,
    name: '28. Pillar Maze (기둥 미로)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 9,
    height: 7,
    description: '4개의 독립된 기둥 사이를 누비며 2개의 공을 정렬하세요.',
    hint: '중앙 통로를 개방된 상태로 유지하세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.#.O.#',
      '#...#...#',
      '#.X.#.X.#',
      '#...#...#',
      '#########',
    ],
  },
  // STAGE 29: TEMPLE GATE (신전의 문)
  {
    id: 29,
    name: '29. Temple Gate (신전의 문)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 9,
    height: 7,
    description: '신전 관문을 통과해 3채의 성소로 공을 배달하세요.',
    hint: '중앙 제단 앞을 막고 있는 공을 먼저 이동시키세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.O.O.#',
      '#...#...#',
      '#.X.X.X.#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 30: INFINITY LOOP (인피니티 루프)
  {
    id: 30,
    name: '30. Infinity Loop (무한 루프)',
    phase: 'Phase 4: Expert',
    phaseCategory: 'Advanced',
    width: 9,
    height: 7,
    description: '8자 모양의 무한 순환 통로에서 공을 순환시키세요.',
    hint: '루프의 교차로를 적극적으로 활용하세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.##O.#',
      '#...##..#',
      '#.X.##X.#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 31: RETRO CLASSIC 3 (애니콜 3호기)
  {
    id: 31,
    name: '31. Retro Classic 3 (애니콜 3호기)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 9,
    height: 7,
    description: '원작 애니콜 푸시푸시 특유의 정교한 3구 배치 클래식 퍼즐입니다.',
    hint: '벽돌 사이 홈으로 공을 하나씩 밀어넣으세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.O.O.#',
      '#..###..#',
      '#..XXX..#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 32: THE CRANE (기중기 창고)
  {
    id: 32,
    name: '32. The Crane (기중기 창고)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 8,
    height: 7,
    description: '기중기 팔처럼 꺾인 좁은 구역에서 공을 섬세하게 조작하세요.',
    hint: '모서리에 끼이기 전에 미리 방향을 틀어야 합니다.',
    grid: [
      '########',
      '#@.....#',
      '#.O.O..#',
      '#...#..#',
      '#.X.##.#',
      '#..X...#',
      '########',
    ],
  },
  // STAGE 33: CASTLE MOAT (성채 해자)
  {
    id: 33,
    name: '33. Castle Moat (성채 해자)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 9,
    height: 7,
    description: '해자로 둘러싸인 안쪽 성채로 3개의 공을 진입시키세요.',
    hint: '성채 입구 통로를 막지 않도록 순서를 계획하세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.O.O.#',
      '#.#.###.#',
      '#...XXX.#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 34: HOURGLASS (모래시계)
  {
    id: 34,
    name: '34. Hourglass (모래시계)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 7,
    height: 7,
    description: '상단 챔버의 공들을 좁은 목을 통과시켜 하단 챔버로 이동시키세요.',
    hint: '좁은 목에 공이 멈추지 않도록 단번에 통과시키세요.',
    grid: [
      '#######',
      '#@....#',
      '#.O.O.#',
      '##...##',
      '#.X.X.#',
      '#.....#',
      '#######',
    ],
  },
  // STAGE 35: WAREHOUSE PRIME (프라임 창고)
  {
    id: 35,
    name: '35. Warehouse Prime (프라임 창고)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 9,
    height: 7,
    description: '3개의 화물을 3개의 지정 독(Dock)에 정확히 입고시키세요.',
    hint: '독의 깊은 곳부터 채우는 것이 정석입니다.',
    grid: [
      '#########',
      '#@......#',
      '#.O.O.O.#',
      '#...#...#',
      '#.XXX...#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 36: GALAXY CORE (은하 코어)
  {
    id: 36,
    name: '36. Galaxy Core (은하 코어)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 8,
    height: 8,
    description: '은하 코어 주위를 궤도 비행하듯 공을 선회시키세요.',
    hint: '중앙 2x2 블록을 회전축으로 활용하세요.',
    grid: [
      '########',
      '#@.....#',
      '#.O.O..#',
      '#..##..#',
      '#..##..#',
      '#.X..X.#',
      '#......#',
      '########',
    ],
  },
  // STAGE 37: LABYRINTH OF NEON (네온 미궁)
  {
    id: 37,
    name: '37. Labyrinth of Neon (네온 미궁)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 8,
    height: 7,
    description: '네온 빛으로 둘러싸인 복합 미궁을 정복하세요.',
    hint: '갈림길마다 한 수 앞을 내다보고 미세요.',
    grid: [
      '########',
      '#@.....#',
      '#.##.O.#',
      '#..#.O.#',
      '#.##.X.#',
      '#....X.#',
      '########',
    ],
  },
  // STAGE 38: TRI-FORCE (트라이포스)
  {
    id: 38,
    name: '38. Tri-Force (트라이포스)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 9,
    height: 8,
    description: '삼각형 배치로 놓인 3개의 공과 3개의 신성한 집.',
    hint: '삼각형의 꼭짓점 방향으로 공을 하나씩 분산시키세요.',
    grid: [
      '#########',
      '#@......#',
      '#...O...#',
      '#.O...O.#',
      '#..#.#..#',
      '#..XXX..#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 39: THE MATRIX (매트릭스 그리드)
  {
    id: 39,
    name: '39. The Matrix (매트릭스 그리드)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 9,
    height: 7,
    description: '격자형 매트릭스 공간에서 2개의 공을 유기적으로 이동시키세요.',
    hint: '공들 간의 연쇄 밀기를 주의 깊게 설계하세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.#.O.#',
      '#...#...#',
      '#.X.#.X.#',
      '#.......#',
      '#########',
    ],
  },
  // STAGE 40: ULTIMATE SOUL (궁극의 소코반)
  {
    id: 40,
    name: '40. Ultimate Soul (궁극의 소코반)',
    phase: 'Phase 5: Master',
    phaseCategory: 'Classic',
    width: 9,
    height: 8,
    description: '푸시푸시 40단계 대망의 최종 챔피언십 스테이지!',
    hint: '모든 클래식 소코반 기법을 총동원하여 4개의 공을 모두 집어넣으세요.',
    grid: [
      '#########',
      '#@......#',
      '#.O.O.O.#',
      '#...#...#',
      '#.X.X.X.#',
      '#...O...#',
      '#...X...#',
      '#########',
    ],
  },
];

console.log('Testing refined candidate stages for solvability...');

let passCount = 0;

candidateStages.forEach((st) => {
  const res = solveStage(st.grid);
  console.log(
    `Stage ${st.id} (${st.name}): Solvable = ${res.solvable}, MinMoves = ${res.minMoves}`
  );
  if (res.solvable) {
    passCount++;
  } else {
    console.error(`ERROR: Stage ${st.id} is NOT solvable!`);
  }
});

console.log(`TOTAL SOLVABLE STAGES: ${passCount}/${candidateStages.length}`);
